version: '3.8'
# -=-=-=-=-=-=-=-=-=-=VOLUMES=-=-=-=-=-=-=-=-=-=-
volumes:
  data_portfolio:
# -=-=-=-=-=-=-=-=-=-=NETWORKS=-=-=-=-=-=-=-=-=-=-
networks:
  my-proxy-net:
    external:
      name: nginx_network
services:
  # -=-=-=-=-=-=-=-=-=-=FRONTEND=-=-=-=-=-=-=-=-=-=-
  front_portfolio:
    volumes:
      - ./portfolio:/app
    build:
      context: ./portfolio
      dockerfile: ./front.dockerfile
    container_name: frontend_portfolio
    ports:
      - "4700:4700"
    restart: unless-stopped
    networks:
      - my-proxy-net
    depends_on:
      - back_portfolio
  # -=-=-=-=-=-=-=-=-=-=BACKEND=-=-=-=-=-=-=-=-=-=-
  back_portfolio:
    volumes:
      - ./backend:/app
    build:
      context: ./backend
      dockerfile: ./back.dockerfile
    container_name: backend_portfolio
    ports:
      - "4667:4667"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - my-proxy-net
